# Generated by Django 5.2.6 on 2025-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('std_age', models.IntegerField()),
                ('std_city', models.CharField(max_length=100)),
                ('std_email', models.EmailField(max_length=254)),
                ('std_phone_number', models.CharField(max_length=15)),
                ('std_address', models.TextField()),
            ],
        ),
    ]
