from flask import Flask, request, render_template_string # Changed to render_template_string

app = Flask(__name__)
app.secret_key = 'a_very_secret_key_for_session_flashing' # Required for session management, even if not explicitly using flash here

# --- HTML Template (Embedded for single-file Flask app) ---
USER_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; background-color: #f3f4f6; }
        .container { max-width: 600px; }
        .card { background-color: white; padding: 2rem; border-radius: 0.5rem; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); }
    </style>
</head>
<body class="bg-gray-100 flex items-center justify-center min-h-screen">
    <div class="container mx-auto p-4">
        <div class="card">
            <h1 class="text-3xl font-bold text-gray-800 mb-4">Hello, {{ username }}!</h1>
            <p class="text-gray-600">This is a dynamic user page generated by Flask.</p>
            <p class="mt-4"><a href="/" class="text-blue-600 hover:underline">Go back to Home</a></p>
        </div>
    </div>
</body>
</html>
"""


# Adding additional routes to our flask app

@app.route('/')
def hello_world():
    """Home page: Displays a simple 'Hello, World!' message."""
    return '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Home Page</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
        <style>
            body { font-family: 'Inter', sans-serif; background-color: #f3f4f6; }
            .container { max-width: 800px; }
            .nav-link { margin-right: 1.5rem; color: #3b82f6; hover:text-blue-800; text-decoration: none; font-weight: 600; }
            .nav-link:hover { text-decoration: underline; }
            .form-input { padding: 0.5rem; border: 1px solid #d1d5db; border-radius: 0.375rem; width: 100%; max-width: 300px; }
            .btn { background-color: #2563eb; color: white; padding: 0.5rem 1rem; border-radius: 0.375rem; cursor: pointer; transition: background-color 0.2s; }
            .btn:hover { background-color: #1d4ed8; }
        </style>
    </head>
    <body class="bg-gray-100 flex flex-col min-h-screen">
        <header class="bg-blue-600 text-white p-4 shadow-md">
            <nav class="container mx-auto flex justify-between items-center">
                <a href="/" class="text-white text-xl font-bold">My Flask App</a>
                <div>
                    <a href="/" class="nav-link text-white hover:text-blue-200">Home</a>
                    <a href="/about" class="nav-link text-white hover:text-blue-200">About</a>
                    <a href="/services" class="nav-link text-white hover:text-blue-200">Services</a>
                    <a href="/user/Guest" class="nav-link text-white hover:text-blue-200">User Profile (Guest)</a>
                </div>
            </nav>
        </header>

        <main class="flex-grow container mx-auto p-6 flex flex-col items-center justify-center">
            <div class="bg-white p-8 rounded-lg shadow-md text-center">
                <h1 class="text-4xl font-extrabold text-gray-800 mb-6">Hello, World!</h1>
                <p class="text-lg text-gray-700 mb-8">Welcome to a simple Flask application demonstrating various routes.</p>

                <div class="mb-8">
                    <h2 class="text-2xl font-semibold text-gray-700 mb-4">Submit Your Name</h2>
                    <form action="/submit" method="POST" class="space-y-4">
                        <input type="text" name="name" placeholder="Enter your name" class="form-input" required>
                        <button type="submit" class="btn">Submit</button>
                    </form>
                </div>
                <p class="text-sm text-gray-500">Check the URL for dynamic routes like <a href="/user/Alice" class="text-blue-500 hover:underline">/user/Alice</a></p>
            </div>
        </main>

        <footer class="bg-gray-800 text-white p-4 text-center mt-auto shadow-inner">
            <div class="container mx-auto">
                &copy; 2025 My Flask App. All rights reserved.
            </div>
        </footer>
    </body>
    </html>
    '''

@app.route('/about')
def about():
    """About page."""
    return '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>About Page</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
        <style>
            body { font-family: 'Inter', sans-serif; background-color: #f3f4f6; }
            .container { max-width: 800px; }
            .nav-link { margin-right: 1.5rem; color: #3b82f6; hover:text-blue-800; text-decoration: none; font-weight: 600; }
            .nav-link:hover { text-decoration: underline; }
        </style>
    </head>
    <body class="bg-gray-100 flex flex-col min-h-screen">
        <header class="bg-blue-600 text-white p-4 shadow-md">
            <nav class="container mx-auto flex justify-between items-center">
                <a href="/" class="text-white text-xl font-bold">My Flask App</a>
                <div>
                    <a href="/" class="nav-link text-white hover:text-blue-200">Home</a>
                    <a href="/about" class="nav-link text-white hover:text-blue-200">About</a>
                    <a href="/services" class="nav-link text-white hover:text-blue-200">Services</a>
                    <a href="/user/Guest" class="nav-link text-white hover:text-blue-200">User Profile (Guest)</a>
                </div>
            </nav>
        </header>

        <main class="flex-grow container mx-auto p-6 flex flex-col items-center justify-center">
            <div class="bg-white p-8 rounded-lg shadow-md text-center">
                <h1 class="text-4xl font-extrabold text-gray-800 mb-6">About Us</h1>
                <p class="text-lg text-gray-700 mb-4">This is a simple demonstration of different routes in a Flask application.</p>
                <p class="text-lg text-gray-700">Flask is a micro-framework for Python, ideal for building small to medium-sized web applications.</p>
                <p class="mt-8"><a href="/" class="text-blue-600 hover:underline">Go back to Home</a></p>
            </div>
        </main>

        <footer class="bg-gray-800 text-white p-4 text-center mt-auto shadow-inner">
            <div class="container mx-auto">
                &copy; 2025 My Flask App. All rights reserved.
            </div>
        </footer>
    </body>
    </html>
    '''

@app.route('/services')
def services():
    """Services page."""
    return '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Services Page</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
        <style>
            body { font-family: 'Inter', sans-serif; background-color: #f3f4f6; }
            .container { max-width: 800px; }
            .nav-link { margin-right: 1.5rem; color: #3b82f6; hover:text-blue-800; text-decoration: none; font-weight: 600; }
            .nav-link:hover { text-decoration: underline; }
        </style>
    </head>
    <body class="bg-gray-100 flex flex-col min-h-screen">
        <header class="bg-blue-600 text-white p-4 shadow-md">
            <nav class="container mx-auto flex justify-between items-center">
                <a href="/" class="text-white text-xl font-bold">My Flask App</a>
                <div>
                    <a href="/" class="nav-link text-white hover:text-blue-200">Home</a>
                    <a href="/about" class="nav-link text-white hover:text-blue-200">About</a>
                    <a href="/services" class="nav-link text-white hover:text-blue-200">Services</a>
                    <a href="/user/Guest" class="nav-link text-white hover:text-blue-200">User Profile (Guest)</a>
                </div>
            </nav>
        </header>

        <main class="flex-grow container mx-auto p-6 flex flex-col items-center justify-center">
            <div class="bg-white p-8 rounded-lg shadow-md text-center">
                <h1 class="text-4xl font-extrabold text-gray-800 mb-6">Our Services</h1>
                <ul class="list-disc list-inside text-lg text-gray-700 mb-4 text-left">
                    <li>Web Development</li>
                    <li>API Design</li>
                    <li>Data Processing</li>
                    <li>Python Consulting</li>
                </ul>
                <p class="mt-8"><a href="/" class="text-blue-600 hover:underline">Go back to Home</a></p>
            </div>
        </main>

        <footer class="bg-gray-800 text-white p-4 text-center mt-auto shadow-inner">
            <div class="container mx-auto">
                &copy; 2025 My Flask App. All rights reserved.
            </div>
        </footer>
    </body>
    </html>
    '''

@app.route('/submit', methods=['POST'])
def submit():
    """Handles form submission from the home page."""
    # Ensure 'name' is in the form data before accessing
    if 'name' in request.form:
        name = request.form['name']
        return f'''
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Submission Result</title>
            <script src="https://cdn.tailwindcss.com"></script>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
            <style>
                body { font-family: 'Inter', sans-serif; background-color: #f3f4f6; }
                .container { max-width: 600px; }
                .card { background-color: white; padding: 2rem; border-radius: 0.5rem; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); }
            </style>
        </head>
        <body class="bg-gray-100 flex items-center justify-center min-h-screen">
            <div class="container mx-auto p-4">
                <div class="card text-center">
                    <h1 class="text-3xl font-bold text-gray-800 mb-4">Hello, {name}!</h1>
                    <p class="text-gray-600">Your name has been submitted successfully.</p>
                    <p class="mt-4"><a href="/" class="text-blue-600 hover:underline">Go back to Home</a></p>
                </div>
            </div>
        </body>
        </html>
        '''
    else:
        return "Name not provided in the form.", 400 # Bad request if 'name' is missing


@app.route('/user/<username>') # Renamed variable to avoid conflict with function name
def user(username): # Corrected: passed username as keyword argument
    """Dynamic route to display a user's profile page."""
    # Pass the variable as a keyword argument directly
    return render_template_string(USER_HTML_TEMPLATE, username=username)

if __name__ == '__main__':
    app.run(debug=True) # Run the Flask development server
