# Get 2 no for user, get square and add
i = int(input("Enter number i:"))
j = int(input("Enter number j:"))
print("Square of i = "+str(i*i))
print("Square of j = "+str(j*j))
add = (j*j) + (i*i)
print("Addition of both squares = "+str(add))
print("Cube of i = "+str(i*i*i))
print("Cube of j = "+str(j*j*j))
add_1 = (j*j*j) + (i*i*i)
print("Addition of both cubes = "+str(add_1))